version: "3.4"
services:

  mysql:
    image: "mysql:5.6"
    environment:
      - MYSQL_DATABASE=fake_spotify_ruby_api_development
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"