version: "3.4"
services:

  mysql:
    image: "mysql:5.6"
    environment:
      - MYSQL_DATABASE=fake-spotify
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
