---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/albums":
    get:
      summary: Retrieves all albums
      tags:
      - Albums
      responses:
        '200':
          description: get albums
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  copyright:
                    type: string
                  year:
                    type: integer
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
